### PR TITLE
add short names

### PR DESCRIPTION
**Pull request by ocefpaf**
I added a new "short_name" field for easier access when handling this as a dictionary. Hope it is OK, it should not disrupt how this JSON is used at the moment.

### CODE REVIEW

**Comment by adamml** [comment]
@fullergalway any thoughts on this? Does it work with how you're using the JSON?

**Comment by fullergalway** [comment]
Looks good to me; no problem from my side but I think the erddap.js file should be committed with same changes too?

**Comment by adamml** [comment]
@fullergalway Yes. I'll update the JSON Schema and the build to do that, and then merge the PR

**Comment by ocefpaf** [comment]
Thanks!

**Pull request merged**
